stages:
  - build
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_package:
  stage: build
  image: alpine:latest
  before_script:
    - apk add --no-cache bash tar curl jq
  script:
    - bash release.sh build
  artifacts:
    paths:
      - "*.tar.gz"
    expire_in: 1 week

create_release:
  stage: release
  image: alpine:latest
  needs:
    - build_package
  rules:
    - if: $CI_COMMIT_TAG   # Only run on tags
  before_script:
    - apk add --no-cache bash tar curl jq
  script:
    - bash release.sh release
