name: Sync from GitLab

on:
  schedule:
    # Synchronise toutes les heures
    - cron: '0 * * * *'
  workflow_dispatch:
    # Permet de déclencher manuellement

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://gitlab.villejuif.fr/depots-public/gitlabmonitor.git
          git remote -v

      - name: Fetch from GitLab
        run: |
          git fetch gitlab --tags
          git fetch gitlab --all

      - name: Backup workflow file
        run: |
          mkdir -p /tmp/github-backup
          cp -r .github /tmp/github-backup/ 2>/dev/null || echo "No .github directory to backup"

      - name: Sync all branches
        run: |
          # Synchroniser toutes les branches
          for branch in $(git branch -r --format='%(refname:lstrip=3)' | grep '^gitlab/' | grep -v 'HEAD'); do
            remote_branch=${branch#gitlab/}
            echo "Synchronizing branch: $remote_branch"
            
            # Créer/mettre à jour la branche locale
            git checkout -B $remote_branch gitlab/$remote_branch
            
            # Restaurer les workflows GitHub si nécessaire
            if [ ! -d ".github" ] && [ -d "/tmp/github-backup/.github" ]; then
              echo "Restoring GitHub workflows for branch $remote_branch"
              cp -r /tmp/github-backup/.github ./
              git add .github/
              git commit -m "Restore GitHub workflows" || echo "No changes to commit"
            fi
            
            # Pousser vers GitHub
            git push origin $remote_branch --force-with-lease
          done

      - name: Restore workflows on main branch
        run: |
          git checkout main || git checkout master
          if [ ! -d ".github" ] && [ -d "/tmp/github-backup/.github" ]; then
            echo "Restoring GitHub workflows on main branch"
            cp -r /tmp/github-backup/.github ./
            git add .github/
            git commit -m "Restore GitHub workflows" || echo "No changes to commit"
            git push origin HEAD --force-with-lease
          fi

      - name: Sync tags
        run: |
          # Synchroniser tous les tags
          git push origin --tags --force-with-lease

      - name: Return to main branch
        run: |
          git checkout main || git checkout master
